name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Install dependencies
        run: sudo apt-get install -y fpc lcl

      - name: Compile
        run: lazbuild src/Project1.lpi

      - name: Bundle
        run: |
          BUNDLEDIR=pacman-${{ github.ref_name }}-linux
          mkdir -p "$BUNDLEDIR"
          cp out/Project1 "${BUNDLEDIR}/pacman"
          cp -r gfx maps "$BUNDLEDIR"
          zip -r "${BUNDLEDIR}.zip" "${BUNDLEDIR}"

      - name: Upload
        run: |
          upload_url=$(
            curl -L https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ github.ref_name }} \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" | jq -r .upload_url
          )
          # remove suffix from returned url
          upload_url=${upload_url/{*/}

          zipname=pacman-${{ github.ref_name }}-linux.zip
          curl -L ${upload_url}?name=$(echo "$zipname" | sed -e 's/%/%25/g' -e 's/\+/%2B/g' -e 's/ /%20/g') \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}"\
            -H "Content-Type: application/octet-stream" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --data-binary "@$zipname"
